// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_BLUSCREEN_H
#define UI_BLUSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BluScreen
extern void ui_BluScreen_screen_init(void);
extern void ui_BluScreen_screen_destroy(void);
extern void ui_event_BluScreen(lv_event_t * e);
extern lv_obj_t * ui_BluScreen;
extern lv_obj_t * ui_TopBar1;
extern lv_obj_t * ui_ClockLabel1;
extern lv_obj_t * ui_BatteryGroup1;
extern lv_obj_t * ui_batteryIcon1;
extern lv_obj_t * ui_BatteryLable1;
extern lv_obj_t * ui_MainArea1;
extern lv_obj_t * ui_WifiLable1;
extern lv_obj_t * ui_WifiIcon1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

