// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_BluScreen = NULL;
lv_obj_t * ui_TopBar1 = NULL;
lv_obj_t * ui_ClockLabel1 = NULL;
lv_obj_t * ui_BatteryGroup1 = NULL;
lv_obj_t * ui_batteryIcon1 = NULL;
lv_obj_t * ui_BatteryLable1 = NULL;
lv_obj_t * ui_MainArea1 = NULL;
lv_obj_t * ui_WifiLable1 = NULL;
lv_obj_t * ui_WifiIcon1 = NULL;
// event funtions
void ui_event_BluScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_BootScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_BootScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_WifiScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WifiScreen_screen_init);
    }
}

// build funtions

void ui_BluScreen_screen_init(void)
{
    ui_BluScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_BluScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar1 = lv_obj_create(ui_BluScreen);
    lv_obj_remove_style_all(ui_TopBar1);
    lv_obj_set_width(ui_TopBar1, 453);
    lv_obj_set_height(ui_TopBar1, 54);
    lv_obj_set_x(ui_TopBar1, -6);
    lv_obj_set_y(ui_TopBar1, -124);
    lv_obj_set_align(ui_TopBar1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopBar1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopBar1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TopBar1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockLabel1 = lv_label_create(ui_TopBar1);
    lv_obj_set_width(ui_ClockLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel1, -1);
    lv_obj_set_y(ui_ClockLabel1, 0);
    lv_obj_set_align(ui_ClockLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel1, "Clock");

    ui_BatteryGroup1 = lv_obj_create(ui_TopBar1);
    lv_obj_remove_style_all(ui_BatteryGroup1);
    lv_obj_set_width(ui_BatteryGroup1, 172);
    lv_obj_set_height(ui_BatteryGroup1, 38);
    lv_obj_set_x(ui_BatteryGroup1, -4);
    lv_obj_set_y(ui_BatteryGroup1, 8);
    lv_obj_set_align(ui_BatteryGroup1, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryGroup1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryGroup1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BatteryGroup1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BatteryGroup1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryIcon1 = lv_image_create(ui_BatteryGroup1);
    lv_image_set_src(ui_batteryIcon1, &ui_img_battery_png);
    lv_obj_set_width(ui_batteryIcon1, 83);
    lv_obj_set_height(ui_batteryIcon1, 40);
    lv_obj_set_x(ui_batteryIcon1, -20);
    lv_obj_set_y(ui_batteryIcon1, 20);
    lv_obj_set_align(ui_batteryIcon1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_batteryIcon1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_batteryIcon1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_batteryIcon1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batteryIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_batteryIcon1, 20);

    ui_BatteryLable1 = lv_label_create(ui_BatteryGroup1);
    lv_obj_set_width(ui_BatteryLable1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLable1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatteryLable1, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryLable1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryLable1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BatteryLable1, "Battery text");

    ui_MainArea1 = lv_obj_create(ui_BluScreen);
    lv_obj_remove_style_all(ui_MainArea1);
    lv_obj_set_width(ui_MainArea1, 321);
    lv_obj_set_height(ui_MainArea1, 230);
    lv_obj_set_x(ui_MainArea1, -69);
    lv_obj_set_y(ui_MainArea1, 8);
    lv_obj_set_align(ui_MainArea1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainArea1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLable1 = lv_label_create(ui_MainArea1);
    lv_obj_set_width(ui_WifiLable1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLable1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLable1, 1);
    lv_obj_set_y(ui_WifiLable1, -2);
    lv_obj_set_align(ui_WifiLable1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WifiLable1, "Blue tooth");
    lv_obj_set_style_text_color(ui_WifiLable1, lv_color_hex(0xD110E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLable1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon1 = lv_image_create(ui_MainArea1);
    lv_image_set_src(ui_WifiIcon1, &ui_img_blu_png);
    lv_obj_set_width(ui_WifiIcon1, 130);
    lv_obj_set_height(ui_WifiIcon1, 125);
    lv_obj_set_x(ui_WifiIcon1, 1);
    lv_obj_set_y(ui_WifiIcon1, 28);
    lv_obj_set_align(ui_WifiIcon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIcon1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_WifiIcon1, 20, 20);
    lv_image_set_inner_align(ui_WifiIcon1, LV_IMAGE_ALIGN_TOP_LEFT);

    lv_obj_add_event_cb(ui_BluScreen, ui_event_BluScreen, LV_EVENT_ALL, NULL);

}

void ui_BluScreen_screen_destroy(void)
{
    if(ui_BluScreen) lv_obj_del(ui_BluScreen);

    // NULL screen variables
    ui_BluScreen = NULL;
    ui_TopBar1 = NULL;
    ui_ClockLabel1 = NULL;
    ui_BatteryGroup1 = NULL;
    ui_batteryIcon1 = NULL;
    ui_BatteryLable1 = NULL;
    ui_MainArea1 = NULL;
    ui_WifiLable1 = NULL;
    ui_WifiIcon1 = NULL;

}
