// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_BOOTSCREEN_H
#define UI_BOOTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BootScreen
extern void ui_BootScreen_screen_init(void);
extern void ui_BootScreen_screen_destroy(void);
extern void ui_event_BootScreen(lv_event_t * e);
extern lv_obj_t * ui_BootScreen;
extern lv_obj_t * ui_BootImage;
extern lv_obj_t * ui_bootscreenlabel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_BootScreen;
extern lv_obj_t * uic_BootImage;
extern lv_obj_t * uic_bootscreenlabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

