// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_bootscreenlabel;
lv_obj_t * uic_BootImage;
lv_obj_t * uic_BootScreen;
lv_obj_t * ui_BootScreen = NULL;
lv_obj_t * ui_BootImage = NULL;
lv_obj_t * ui_bootscreenlabel = NULL;
// event funtions
void ui_event_BootScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_WifiScreen, LV_SCR_LOAD_ANIM_FADE_ON, 1, 0, &ui_WifiScreen_screen_init);
    }
}

// build funtions

void ui_BootScreen_screen_init(void)
{
    ui_BootScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_BootScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_add_event_cb(ui_BootScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_BootScreen_screen_destroy);

    ui_BootImage = lv_image_create(ui_BootScreen);
    lv_image_set_src(ui_BootImage, &ui_img_bruce_hdc_png);
    lv_obj_set_width(ui_BootImage, 492);
    lv_obj_set_height(ui_BootImage, 322);
    lv_obj_set_align(ui_BootImage, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BootImage, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BootImage, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BootImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BootImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_BootImage, 170);
    lv_image_set_inner_align(ui_BootImage, LV_IMAGE_ALIGN_STRETCH);

    ui_bootscreenlabel = lv_label_create(ui_BootScreen);
    lv_obj_set_width(ui_bootscreenlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bootscreenlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bootscreenlabel, -9);
    lv_obj_set_y(ui_bootscreenlabel, 148);
    lv_obj_set_align(ui_bootscreenlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bootscreenlabel, "LOADING BRUCE PREDATORY FIRMWARE");
    lv_obj_set_style_text_color(ui_bootscreenlabel, lv_color_hex(0x7716C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bootscreenlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BootScreen, ui_event_BootScreen, LV_EVENT_ALL, NULL);
    uic_BootScreen = ui_BootScreen;
    uic_BootImage = ui_BootImage;
    uic_bootscreenlabel = ui_bootscreenlabel;

}

void ui_BootScreen_screen_destroy(void)
{
    if(ui_BootScreen) lv_obj_del(ui_BootScreen);

    // NULL screen variables
    uic_BootScreen = NULL;
    ui_BootScreen = NULL;
    uic_BootImage = NULL;
    ui_BootImage = NULL;
    uic_bootscreenlabel = NULL;
    ui_bootscreenlabel = NULL;

}
