// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_CONNECT_H
#define UI_CONNECT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Connect
extern void ui_Connect_screen_init(void);
extern void ui_Connect_screen_destroy(void);
extern void ui_event_Connect(lv_event_t * e);
extern lv_obj_t * ui_Connect;
extern lv_obj_t * ui_TopBar14;
extern lv_obj_t * ui_ClockLabel14;
extern lv_obj_t * ui_BatteryGroup14;
extern lv_obj_t * ui_batteryIcon14;
extern lv_obj_t * ui_BatteryLable14;
extern lv_obj_t * ui_MainArea14;
extern lv_obj_t * ui_WifiLable14;
extern lv_obj_t * ui_WifiIcon15;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

