// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Config = NULL;
lv_obj_t * ui_TopBar15 = NULL;
lv_obj_t * ui_ClockLabel15 = NULL;
lv_obj_t * ui_BatteryGroup15 = NULL;
lv_obj_t * ui_batteryIcon15 = NULL;
lv_obj_t * ui_BatteryLable15 = NULL;
lv_obj_t * ui_MainArea15 = NULL;
lv_obj_t * ui_WifiLable15 = NULL;
lv_obj_t * ui_WifiIcon16 = NULL;
// event funtions
void ui_event_Config(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_WifiScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_WifiScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Connect, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Connect_screen_init);
    }
}

// build funtions

void ui_Config_screen_init(void)
{
    ui_Config = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Config, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar15 = lv_obj_create(ui_Config);
    lv_obj_remove_style_all(ui_TopBar15);
    lv_obj_set_width(ui_TopBar15, 453);
    lv_obj_set_height(ui_TopBar15, 54);
    lv_obj_set_x(ui_TopBar15, -6);
    lv_obj_set_y(ui_TopBar15, -124);
    lv_obj_set_align(ui_TopBar15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopBar15, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopBar15, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TopBar15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockLabel15 = lv_label_create(ui_TopBar15);
    lv_obj_set_width(ui_ClockLabel15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel15, -1);
    lv_obj_set_y(ui_ClockLabel15, 0);
    lv_obj_set_align(ui_ClockLabel15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel15, "Clock");

    ui_BatteryGroup15 = lv_obj_create(ui_TopBar15);
    lv_obj_remove_style_all(ui_BatteryGroup15);
    lv_obj_set_width(ui_BatteryGroup15, 172);
    lv_obj_set_height(ui_BatteryGroup15, 38);
    lv_obj_set_x(ui_BatteryGroup15, -4);
    lv_obj_set_y(ui_BatteryGroup15, 8);
    lv_obj_set_align(ui_BatteryGroup15, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryGroup15, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryGroup15, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BatteryGroup15, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BatteryGroup15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryIcon15 = lv_image_create(ui_BatteryGroup15);
    lv_image_set_src(ui_batteryIcon15, &ui_img_battery_png);
    lv_obj_set_width(ui_batteryIcon15, 83);
    lv_obj_set_height(ui_batteryIcon15, 40);
    lv_obj_set_x(ui_batteryIcon15, -20);
    lv_obj_set_y(ui_batteryIcon15, 20);
    lv_obj_set_align(ui_batteryIcon15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_batteryIcon15, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_batteryIcon15, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_batteryIcon15, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batteryIcon15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_batteryIcon15, 20);

    ui_BatteryLable15 = lv_label_create(ui_BatteryGroup15);
    lv_obj_set_width(ui_BatteryLable15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLable15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatteryLable15, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryLable15, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryLable15, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BatteryLable15, "Battery text");

    ui_MainArea15 = lv_obj_create(ui_Config);
    lv_obj_remove_style_all(ui_MainArea15);
    lv_obj_set_width(ui_MainArea15, 321);
    lv_obj_set_height(ui_MainArea15, 230);
    lv_obj_set_x(ui_MainArea15, -69);
    lv_obj_set_y(ui_MainArea15, 8);
    lv_obj_set_align(ui_MainArea15, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainArea15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLable15 = lv_label_create(ui_MainArea15);
    lv_obj_set_width(ui_WifiLable15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLable15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLable15, 1);
    lv_obj_set_y(ui_WifiLable15, -2);
    lv_obj_set_align(ui_WifiLable15, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WifiLable15, "Config");
    lv_obj_set_style_text_color(ui_WifiLable15, lv_color_hex(0xD110E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLable15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon16 = lv_image_create(ui_MainArea15);
    lv_image_set_src(ui_WifiIcon16, &ui_img_config_png);
    lv_obj_set_width(ui_WifiIcon16, 130);
    lv_obj_set_height(ui_WifiIcon16, 125);
    lv_obj_set_x(ui_WifiIcon16, 1);
    lv_obj_set_y(ui_WifiIcon16, 28);
    lv_obj_set_align(ui_WifiIcon16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIcon16, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiIcon16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_WifiIcon16, 20, 20);
    lv_image_set_inner_align(ui_WifiIcon16, LV_IMAGE_ALIGN_TOP_LEFT);

    lv_obj_add_event_cb(ui_Config, ui_event_Config, LV_EVENT_ALL, NULL);

}

void ui_Config_screen_destroy(void)
{
    if(ui_Config) lv_obj_del(ui_Config);

    // NULL screen variables
    ui_Config = NULL;
    ui_TopBar15 = NULL;
    ui_ClockLabel15 = NULL;
    ui_BatteryGroup15 = NULL;
    ui_batteryIcon15 = NULL;
    ui_BatteryLable15 = NULL;
    ui_MainArea15 = NULL;
    ui_WifiLable15 = NULL;
    ui_WifiIcon16 = NULL;

}
