// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_CONFIG_H
#define UI_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Config
extern void ui_Config_screen_init(void);
extern void ui_Config_screen_destroy(void);
extern void ui_event_Config(lv_event_t * e);
extern lv_obj_t * ui_Config;
extern lv_obj_t * ui_TopBar15;
extern lv_obj_t * ui_ClockLabel15;
extern lv_obj_t * ui_BatteryGroup15;
extern lv_obj_t * ui_batteryIcon15;
extern lv_obj_t * ui_BatteryLable15;
extern lv_obj_t * ui_MainArea15;
extern lv_obj_t * ui_WifiLable15;
extern lv_obj_t * ui_WifiIcon16;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

