// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Clock = NULL;
lv_obj_t * ui_TopBar13 = NULL;
lv_obj_t * ui_ClockLabel13 = NULL;
lv_obj_t * ui_BatteryGroup13 = NULL;
lv_obj_t * ui_batteryIcon13 = NULL;
lv_obj_t * ui_BatteryLable13 = NULL;
lv_obj_t * ui_MainArea13 = NULL;
lv_obj_t * ui_WifiLable13 = NULL;
lv_obj_t * ui_WifiIcon14 = NULL;
// event funtions
void ui_event_Clock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Connect, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Connect_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Others, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Others_screen_init);
    }
}

// build funtions

void ui_Clock_screen_init(void)
{
    ui_Clock = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Clock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar13 = lv_obj_create(ui_Clock);
    lv_obj_remove_style_all(ui_TopBar13);
    lv_obj_set_width(ui_TopBar13, 453);
    lv_obj_set_height(ui_TopBar13, 54);
    lv_obj_set_x(ui_TopBar13, -6);
    lv_obj_set_y(ui_TopBar13, -124);
    lv_obj_set_align(ui_TopBar13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopBar13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopBar13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TopBar13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockLabel13 = lv_label_create(ui_TopBar13);
    lv_obj_set_width(ui_ClockLabel13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel13, -1);
    lv_obj_set_y(ui_ClockLabel13, 0);
    lv_obj_set_align(ui_ClockLabel13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel13, "Clock");

    ui_BatteryGroup13 = lv_obj_create(ui_TopBar13);
    lv_obj_remove_style_all(ui_BatteryGroup13);
    lv_obj_set_width(ui_BatteryGroup13, 172);
    lv_obj_set_height(ui_BatteryGroup13, 38);
    lv_obj_set_x(ui_BatteryGroup13, -4);
    lv_obj_set_y(ui_BatteryGroup13, 8);
    lv_obj_set_align(ui_BatteryGroup13, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryGroup13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryGroup13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BatteryGroup13, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BatteryGroup13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryIcon13 = lv_image_create(ui_BatteryGroup13);
    lv_image_set_src(ui_batteryIcon13, &ui_img_battery_png);
    lv_obj_set_width(ui_batteryIcon13, 83);
    lv_obj_set_height(ui_batteryIcon13, 40);
    lv_obj_set_x(ui_batteryIcon13, -20);
    lv_obj_set_y(ui_batteryIcon13, 20);
    lv_obj_set_align(ui_batteryIcon13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_batteryIcon13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_batteryIcon13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_batteryIcon13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batteryIcon13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_batteryIcon13, 20);

    ui_BatteryLable13 = lv_label_create(ui_BatteryGroup13);
    lv_obj_set_width(ui_BatteryLable13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLable13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatteryLable13, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryLable13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryLable13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BatteryLable13, "Battery text");

    ui_MainArea13 = lv_obj_create(ui_Clock);
    lv_obj_remove_style_all(ui_MainArea13);
    lv_obj_set_width(ui_MainArea13, 321);
    lv_obj_set_height(ui_MainArea13, 230);
    lv_obj_set_x(ui_MainArea13, -69);
    lv_obj_set_y(ui_MainArea13, 8);
    lv_obj_set_align(ui_MainArea13, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainArea13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLable13 = lv_label_create(ui_MainArea13);
    lv_obj_set_width(ui_WifiLable13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLable13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLable13, 1);
    lv_obj_set_y(ui_WifiLable13, -2);
    lv_obj_set_align(ui_WifiLable13, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WifiLable13, "Clock");
    lv_obj_set_style_text_color(ui_WifiLable13, lv_color_hex(0xD110E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLable13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon14 = lv_image_create(ui_MainArea13);
    lv_image_set_src(ui_WifiIcon14, &ui_img_clock_png);
    lv_obj_set_width(ui_WifiIcon14, 130);
    lv_obj_set_height(ui_WifiIcon14, 125);
    lv_obj_set_x(ui_WifiIcon14, 1);
    lv_obj_set_y(ui_WifiIcon14, 28);
    lv_obj_set_align(ui_WifiIcon14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIcon14, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiIcon14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_WifiIcon14, 20, 20);
    lv_image_set_inner_align(ui_WifiIcon14, LV_IMAGE_ALIGN_TOP_LEFT);

    lv_obj_add_event_cb(ui_Clock, ui_event_Clock, LV_EVENT_ALL, NULL);

}

void ui_Clock_screen_destroy(void)
{
    if(ui_Clock) lv_obj_del(ui_Clock);

    // NULL screen variables
    ui_Clock = NULL;
    ui_TopBar13 = NULL;
    ui_ClockLabel13 = NULL;
    ui_BatteryGroup13 = NULL;
    ui_batteryIcon13 = NULL;
    ui_BatteryLable13 = NULL;
    ui_MainArea13 = NULL;
    ui_WifiLable13 = NULL;
    ui_WifiIcon14 = NULL;

}
