// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_CLOCK_H
#define UI_CLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Clock
extern void ui_Clock_screen_init(void);
extern void ui_Clock_screen_destroy(void);
extern void ui_event_Clock(lv_event_t * e);
extern lv_obj_t * ui_Clock;
extern lv_obj_t * ui_TopBar13;
extern lv_obj_t * ui_ClockLabel13;
extern lv_obj_t * ui_BatteryGroup13;
extern lv_obj_t * ui_batteryIcon13;
extern lv_obj_t * ui_BatteryLable13;
extern lv_obj_t * ui_MainArea13;
extern lv_obj_t * ui_WifiLable13;
extern lv_obj_t * ui_WifiIcon14;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

