// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Connect = NULL;
lv_obj_t * ui_TopBar14 = NULL;
lv_obj_t * ui_ClockLabel14 = NULL;
lv_obj_t * ui_BatteryGroup14 = NULL;
lv_obj_t * ui_batteryIcon14 = NULL;
lv_obj_t * ui_BatteryLable14 = NULL;
lv_obj_t * ui_MainArea14 = NULL;
lv_obj_t * ui_WifiLable14 = NULL;
lv_obj_t * ui_WifiIcon15 = NULL;
// event funtions
void ui_event_Connect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Config, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Config_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Clock, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Clock_screen_init);
    }
}

// build funtions

void ui_Connect_screen_init(void)
{
    ui_Connect = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Connect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar14 = lv_obj_create(ui_Connect);
    lv_obj_remove_style_all(ui_TopBar14);
    lv_obj_set_width(ui_TopBar14, 453);
    lv_obj_set_height(ui_TopBar14, 54);
    lv_obj_set_x(ui_TopBar14, -6);
    lv_obj_set_y(ui_TopBar14, -124);
    lv_obj_set_align(ui_TopBar14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopBar14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopBar14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TopBar14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockLabel14 = lv_label_create(ui_TopBar14);
    lv_obj_set_width(ui_ClockLabel14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel14, -1);
    lv_obj_set_y(ui_ClockLabel14, 0);
    lv_obj_set_align(ui_ClockLabel14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel14, "Clock");

    ui_BatteryGroup14 = lv_obj_create(ui_TopBar14);
    lv_obj_remove_style_all(ui_BatteryGroup14);
    lv_obj_set_width(ui_BatteryGroup14, 172);
    lv_obj_set_height(ui_BatteryGroup14, 38);
    lv_obj_set_x(ui_BatteryGroup14, -4);
    lv_obj_set_y(ui_BatteryGroup14, 8);
    lv_obj_set_align(ui_BatteryGroup14, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryGroup14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryGroup14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BatteryGroup14, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BatteryGroup14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryIcon14 = lv_image_create(ui_BatteryGroup14);
    lv_image_set_src(ui_batteryIcon14, &ui_img_battery_png);
    lv_obj_set_width(ui_batteryIcon14, 83);
    lv_obj_set_height(ui_batteryIcon14, 40);
    lv_obj_set_x(ui_batteryIcon14, -20);
    lv_obj_set_y(ui_batteryIcon14, 20);
    lv_obj_set_align(ui_batteryIcon14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_batteryIcon14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_batteryIcon14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_batteryIcon14, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batteryIcon14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_batteryIcon14, 20);

    ui_BatteryLable14 = lv_label_create(ui_BatteryGroup14);
    lv_obj_set_width(ui_BatteryLable14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLable14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatteryLable14, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryLable14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryLable14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BatteryLable14, "Battery text");

    ui_MainArea14 = lv_obj_create(ui_Connect);
    lv_obj_remove_style_all(ui_MainArea14);
    lv_obj_set_width(ui_MainArea14, 321);
    lv_obj_set_height(ui_MainArea14, 230);
    lv_obj_set_x(ui_MainArea14, -69);
    lv_obj_set_y(ui_MainArea14, 8);
    lv_obj_set_align(ui_MainArea14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainArea14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLable14 = lv_label_create(ui_MainArea14);
    lv_obj_set_width(ui_WifiLable14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLable14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLable14, 1);
    lv_obj_set_y(ui_WifiLable14, -2);
    lv_obj_set_align(ui_WifiLable14, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WifiLable14, "Connect");
    lv_obj_set_style_text_color(ui_WifiLable14, lv_color_hex(0xD110E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLable14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon15 = lv_image_create(ui_MainArea14);
    lv_image_set_src(ui_WifiIcon15, &ui_img_connect_png);
    lv_obj_set_width(ui_WifiIcon15, 130);
    lv_obj_set_height(ui_WifiIcon15, 125);
    lv_obj_set_x(ui_WifiIcon15, 1);
    lv_obj_set_y(ui_WifiIcon15, 28);
    lv_obj_set_align(ui_WifiIcon15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIcon15, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiIcon15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_WifiIcon15, 20, 20);
    lv_image_set_inner_align(ui_WifiIcon15, LV_IMAGE_ALIGN_TOP_LEFT);

    lv_obj_add_event_cb(ui_Connect, ui_event_Connect, LV_EVENT_ALL, NULL);

}

void ui_Connect_screen_destroy(void)
{
    if(ui_Connect) lv_obj_del(ui_Connect);

    // NULL screen variables
    ui_Connect = NULL;
    ui_TopBar14 = NULL;
    ui_ClockLabel14 = NULL;
    ui_BatteryGroup14 = NULL;
    ui_batteryIcon14 = NULL;
    ui_BatteryLable14 = NULL;
    ui_MainArea14 = NULL;
    ui_WifiLable14 = NULL;
    ui_WifiIcon15 = NULL;

}
