// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_ETHERNET_H
#define UI_ETHERNET_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Ethernet
extern void ui_Ethernet_screen_init(void);
extern void ui_Ethernet_screen_destroy(void);
extern void ui_event_Ethernet(lv_event_t * e);
extern lv_obj_t * ui_Ethernet;
extern lv_obj_t * ui_TopBar2;
extern lv_obj_t * ui_ClockLabel2;
extern lv_obj_t * ui_BatteryGroup2;
extern lv_obj_t * ui_batteryIcon2;
extern lv_obj_t * ui_BatteryLable2;
extern lv_obj_t * ui_MainArea2;
extern lv_obj_t * ui_WifiLable2;
extern lv_obj_t * ui_WifiIcon3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

