// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Ethernet = NULL;
lv_obj_t * ui_TopBar2 = NULL;
lv_obj_t * ui_ClockLabel2 = NULL;
lv_obj_t * ui_BatteryGroup2 = NULL;
lv_obj_t * ui_batteryIcon2 = NULL;
lv_obj_t * ui_BatteryLable2 = NULL;
lv_obj_t * ui_MainArea2 = NULL;
lv_obj_t * ui_WifiLable2 = NULL;
lv_obj_t * ui_WifiIcon3 = NULL;
// event funtions
void ui_event_Ethernet(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_RadioFreq, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_RadioFreq_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_BluScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_BluScreen_screen_init);
    }
}

// build funtions

void ui_Ethernet_screen_init(void)
{
    ui_Ethernet = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Ethernet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar2 = lv_obj_create(ui_Ethernet);
    lv_obj_remove_style_all(ui_TopBar2);
    lv_obj_set_width(ui_TopBar2, 453);
    lv_obj_set_height(ui_TopBar2, 54);
    lv_obj_set_x(ui_TopBar2, -6);
    lv_obj_set_y(ui_TopBar2, -124);
    lv_obj_set_align(ui_TopBar2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopBar2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopBar2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TopBar2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockLabel2 = lv_label_create(ui_TopBar2);
    lv_obj_set_width(ui_ClockLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel2, -1);
    lv_obj_set_y(ui_ClockLabel2, 0);
    lv_obj_set_align(ui_ClockLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel2, "Clock");

    ui_BatteryGroup2 = lv_obj_create(ui_TopBar2);
    lv_obj_remove_style_all(ui_BatteryGroup2);
    lv_obj_set_width(ui_BatteryGroup2, 172);
    lv_obj_set_height(ui_BatteryGroup2, 38);
    lv_obj_set_x(ui_BatteryGroup2, -4);
    lv_obj_set_y(ui_BatteryGroup2, 8);
    lv_obj_set_align(ui_BatteryGroup2, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryGroup2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryGroup2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BatteryGroup2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BatteryGroup2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryIcon2 = lv_image_create(ui_BatteryGroup2);
    lv_image_set_src(ui_batteryIcon2, &ui_img_battery_png);
    lv_obj_set_width(ui_batteryIcon2, 83);
    lv_obj_set_height(ui_batteryIcon2, 40);
    lv_obj_set_x(ui_batteryIcon2, -20);
    lv_obj_set_y(ui_batteryIcon2, 20);
    lv_obj_set_align(ui_batteryIcon2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_batteryIcon2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_batteryIcon2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_batteryIcon2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batteryIcon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_batteryIcon2, 20);

    ui_BatteryLable2 = lv_label_create(ui_BatteryGroup2);
    lv_obj_set_width(ui_BatteryLable2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLable2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatteryLable2, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryLable2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryLable2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BatteryLable2, "Battery text");

    ui_MainArea2 = lv_obj_create(ui_Ethernet);
    lv_obj_remove_style_all(ui_MainArea2);
    lv_obj_set_width(ui_MainArea2, 321);
    lv_obj_set_height(ui_MainArea2, 230);
    lv_obj_set_x(ui_MainArea2, -69);
    lv_obj_set_y(ui_MainArea2, 8);
    lv_obj_set_align(ui_MainArea2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainArea2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLable2 = lv_label_create(ui_MainArea2);
    lv_obj_set_width(ui_WifiLable2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLable2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLable2, 1);
    lv_obj_set_y(ui_WifiLable2, -2);
    lv_obj_set_align(ui_WifiLable2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WifiLable2, "Ethernet");
    lv_obj_set_style_text_color(ui_WifiLable2, lv_color_hex(0xD110E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLable2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon3 = lv_image_create(ui_MainArea2);
    lv_image_set_src(ui_WifiIcon3, &ui_img_ethernet_png);
    lv_obj_set_width(ui_WifiIcon3, 130);
    lv_obj_set_height(ui_WifiIcon3, 125);
    lv_obj_set_x(ui_WifiIcon3, 1);
    lv_obj_set_y(ui_WifiIcon3, 28);
    lv_obj_set_align(ui_WifiIcon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIcon3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiIcon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_WifiIcon3, 20, 20);
    lv_image_set_inner_align(ui_WifiIcon3, LV_IMAGE_ALIGN_TOP_LEFT);

    lv_obj_add_event_cb(ui_Ethernet, ui_event_Ethernet, LV_EVENT_ALL, NULL);

}

void ui_Ethernet_screen_destroy(void)
{
    if(ui_Ethernet) lv_obj_del(ui_Ethernet);

    // NULL screen variables
    ui_Ethernet = NULL;
    ui_TopBar2 = NULL;
    ui_ClockLabel2 = NULL;
    ui_BatteryGroup2 = NULL;
    ui_batteryIcon2 = NULL;
    ui_BatteryLable2 = NULL;
    ui_MainArea2 = NULL;
    ui_WifiLable2 = NULL;
    ui_WifiIcon3 = NULL;

}
