// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_FMRADIO_H
#define UI_FMRADIO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_FMRadio
extern void ui_FMRadio_screen_init(void);
extern void ui_FMRadio_screen_destroy(void);
extern void ui_event_FMRadio(lv_event_t * e);
extern lv_obj_t * ui_FMRadio;
extern lv_obj_t * ui_TopBar6;
extern lv_obj_t * ui_ClockLabel6;
extern lv_obj_t * ui_BatteryGroup6;
extern lv_obj_t * ui_batteryIcon6;
extern lv_obj_t * ui_BatteryLable6;
extern lv_obj_t * ui_MainArea6;
extern lv_obj_t * ui_WifiLable6;
extern lv_obj_t * ui_WifiIcon7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

