// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_FILES_H
#define UI_FILES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Files
extern void ui_Files_screen_init(void);
extern void ui_Files_screen_destroy(void);
extern void ui_event_Files(lv_event_t * e);
extern lv_obj_t * ui_Files;
extern lv_obj_t * ui_TopBar7;
extern lv_obj_t * ui_ClockLabel7;
extern lv_obj_t * ui_BatteryGroup7;
extern lv_obj_t * ui_batteryIcon7;
extern lv_obj_t * ui_BatteryLable7;
extern lv_obj_t * ui_MainArea7;
extern lv_obj_t * ui_WifiLable7;
extern lv_obj_t * ui_WifiIcon8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

