// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_FMRadio = NULL;
lv_obj_t * ui_TopBar6 = NULL;
lv_obj_t * ui_ClockLabel6 = NULL;
lv_obj_t * ui_BatteryGroup6 = NULL;
lv_obj_t * ui_batteryIcon6 = NULL;
lv_obj_t * ui_BatteryLable6 = NULL;
lv_obj_t * ui_MainArea6 = NULL;
lv_obj_t * ui_WifiLable6 = NULL;
lv_obj_t * ui_WifiIcon7 = NULL;
// event funtions
void ui_event_FMRadio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Files, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Files_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_InfraRed, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_InfraRed_screen_init);
    }
}

// build funtions

void ui_FMRadio_screen_init(void)
{
    ui_FMRadio = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_FMRadio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar6 = lv_obj_create(ui_FMRadio);
    lv_obj_remove_style_all(ui_TopBar6);
    lv_obj_set_width(ui_TopBar6, 453);
    lv_obj_set_height(ui_TopBar6, 54);
    lv_obj_set_x(ui_TopBar6, -6);
    lv_obj_set_y(ui_TopBar6, -124);
    lv_obj_set_align(ui_TopBar6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopBar6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopBar6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TopBar6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockLabel6 = lv_label_create(ui_TopBar6);
    lv_obj_set_width(ui_ClockLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel6, -1);
    lv_obj_set_y(ui_ClockLabel6, 0);
    lv_obj_set_align(ui_ClockLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel6, "Clock");

    ui_BatteryGroup6 = lv_obj_create(ui_TopBar6);
    lv_obj_remove_style_all(ui_BatteryGroup6);
    lv_obj_set_width(ui_BatteryGroup6, 172);
    lv_obj_set_height(ui_BatteryGroup6, 38);
    lv_obj_set_x(ui_BatteryGroup6, -4);
    lv_obj_set_y(ui_BatteryGroup6, 8);
    lv_obj_set_align(ui_BatteryGroup6, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryGroup6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryGroup6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BatteryGroup6, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BatteryGroup6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryIcon6 = lv_image_create(ui_BatteryGroup6);
    lv_image_set_src(ui_batteryIcon6, &ui_img_battery_png);
    lv_obj_set_width(ui_batteryIcon6, 83);
    lv_obj_set_height(ui_batteryIcon6, 40);
    lv_obj_set_x(ui_batteryIcon6, -20);
    lv_obj_set_y(ui_batteryIcon6, 20);
    lv_obj_set_align(ui_batteryIcon6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_batteryIcon6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_batteryIcon6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_batteryIcon6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batteryIcon6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_batteryIcon6, 20);

    ui_BatteryLable6 = lv_label_create(ui_BatteryGroup6);
    lv_obj_set_width(ui_BatteryLable6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLable6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatteryLable6, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryLable6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryLable6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BatteryLable6, "Battery text");

    ui_MainArea6 = lv_obj_create(ui_FMRadio);
    lv_obj_remove_style_all(ui_MainArea6);
    lv_obj_set_width(ui_MainArea6, 321);
    lv_obj_set_height(ui_MainArea6, 230);
    lv_obj_set_x(ui_MainArea6, -69);
    lv_obj_set_y(ui_MainArea6, 8);
    lv_obj_set_align(ui_MainArea6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainArea6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLable6 = lv_label_create(ui_MainArea6);
    lv_obj_set_width(ui_WifiLable6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLable6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLable6, 1);
    lv_obj_set_y(ui_WifiLable6, -2);
    lv_obj_set_align(ui_WifiLable6, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WifiLable6, "FM");
    lv_obj_set_style_text_color(ui_WifiLable6, lv_color_hex(0xD110E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLable6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon7 = lv_image_create(ui_MainArea6);
    lv_image_set_src(ui_WifiIcon7, &ui_img_fm_png);
    lv_obj_set_width(ui_WifiIcon7, 130);
    lv_obj_set_height(ui_WifiIcon7, 125);
    lv_obj_set_x(ui_WifiIcon7, 1);
    lv_obj_set_y(ui_WifiIcon7, 28);
    lv_obj_set_align(ui_WifiIcon7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIcon7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiIcon7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_WifiIcon7, 20, 20);
    lv_image_set_inner_align(ui_WifiIcon7, LV_IMAGE_ALIGN_TOP_LEFT);

    lv_obj_add_event_cb(ui_FMRadio, ui_event_FMRadio, LV_EVENT_ALL, NULL);

}

void ui_FMRadio_screen_destroy(void)
{
    if(ui_FMRadio) lv_obj_del(ui_FMRadio);

    // NULL screen variables
    ui_FMRadio = NULL;
    ui_TopBar6 = NULL;
    ui_ClockLabel6 = NULL;
    ui_BatteryGroup6 = NULL;
    ui_batteryIcon6 = NULL;
    ui_BatteryLable6 = NULL;
    ui_MainArea6 = NULL;
    ui_WifiLable6 = NULL;
    ui_WifiIcon7 = NULL;

}
