// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Files = NULL;
lv_obj_t * ui_TopBar7 = NULL;
lv_obj_t * ui_ClockLabel7 = NULL;
lv_obj_t * ui_BatteryGroup7 = NULL;
lv_obj_t * ui_batteryIcon7 = NULL;
lv_obj_t * ui_BatteryLable7 = NULL;
lv_obj_t * ui_MainArea7 = NULL;
lv_obj_t * ui_WifiLable7 = NULL;
lv_obj_t * ui_WifiIcon8 = NULL;
// event funtions
void ui_event_Files(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_GPS, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_GPS_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_FMRadio, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_FMRadio_screen_init);
    }
}

// build funtions

void ui_Files_screen_init(void)
{
    ui_Files = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Files, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar7 = lv_obj_create(ui_Files);
    lv_obj_remove_style_all(ui_TopBar7);
    lv_obj_set_width(ui_TopBar7, 453);
    lv_obj_set_height(ui_TopBar7, 54);
    lv_obj_set_x(ui_TopBar7, -6);
    lv_obj_set_y(ui_TopBar7, -124);
    lv_obj_set_align(ui_TopBar7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopBar7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopBar7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TopBar7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockLabel7 = lv_label_create(ui_TopBar7);
    lv_obj_set_width(ui_ClockLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel7, -1);
    lv_obj_set_y(ui_ClockLabel7, 0);
    lv_obj_set_align(ui_ClockLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel7, "Clock");

    ui_BatteryGroup7 = lv_obj_create(ui_TopBar7);
    lv_obj_remove_style_all(ui_BatteryGroup7);
    lv_obj_set_width(ui_BatteryGroup7, 172);
    lv_obj_set_height(ui_BatteryGroup7, 38);
    lv_obj_set_x(ui_BatteryGroup7, -4);
    lv_obj_set_y(ui_BatteryGroup7, 8);
    lv_obj_set_align(ui_BatteryGroup7, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryGroup7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryGroup7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BatteryGroup7, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BatteryGroup7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryIcon7 = lv_image_create(ui_BatteryGroup7);
    lv_image_set_src(ui_batteryIcon7, &ui_img_battery_png);
    lv_obj_set_width(ui_batteryIcon7, 83);
    lv_obj_set_height(ui_batteryIcon7, 40);
    lv_obj_set_x(ui_batteryIcon7, -20);
    lv_obj_set_y(ui_batteryIcon7, 20);
    lv_obj_set_align(ui_batteryIcon7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_batteryIcon7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_batteryIcon7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_batteryIcon7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batteryIcon7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_batteryIcon7, 20);

    ui_BatteryLable7 = lv_label_create(ui_BatteryGroup7);
    lv_obj_set_width(ui_BatteryLable7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLable7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatteryLable7, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryLable7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryLable7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BatteryLable7, "Battery text");

    ui_MainArea7 = lv_obj_create(ui_Files);
    lv_obj_remove_style_all(ui_MainArea7);
    lv_obj_set_width(ui_MainArea7, 321);
    lv_obj_set_height(ui_MainArea7, 230);
    lv_obj_set_x(ui_MainArea7, -69);
    lv_obj_set_y(ui_MainArea7, 8);
    lv_obj_set_align(ui_MainArea7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainArea7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLable7 = lv_label_create(ui_MainArea7);
    lv_obj_set_width(ui_WifiLable7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLable7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLable7, 1);
    lv_obj_set_y(ui_WifiLable7, -2);
    lv_obj_set_align(ui_WifiLable7, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WifiLable7, "Files");
    lv_obj_set_style_text_color(ui_WifiLable7, lv_color_hex(0xD110E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLable7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon8 = lv_image_create(ui_MainArea7);
    lv_image_set_src(ui_WifiIcon8, &ui_img_files_png);
    lv_obj_set_width(ui_WifiIcon8, 130);
    lv_obj_set_height(ui_WifiIcon8, 125);
    lv_obj_set_x(ui_WifiIcon8, 1);
    lv_obj_set_y(ui_WifiIcon8, 28);
    lv_obj_set_align(ui_WifiIcon8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIcon8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiIcon8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_WifiIcon8, 20, 20);
    lv_image_set_inner_align(ui_WifiIcon8, LV_IMAGE_ALIGN_TOP_LEFT);

    lv_obj_add_event_cb(ui_Files, ui_event_Files, LV_EVENT_ALL, NULL);

}

void ui_Files_screen_destroy(void)
{
    if(ui_Files) lv_obj_del(ui_Files);

    // NULL screen variables
    ui_Files = NULL;
    ui_TopBar7 = NULL;
    ui_ClockLabel7 = NULL;
    ui_BatteryGroup7 = NULL;
    ui_batteryIcon7 = NULL;
    ui_BatteryLable7 = NULL;
    ui_MainArea7 = NULL;
    ui_WifiLable7 = NULL;
    ui_WifiIcon8 = NULL;

}
