// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_GPS_H
#define UI_GPS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GPS
extern void ui_GPS_screen_init(void);
extern void ui_GPS_screen_destroy(void);
extern void ui_event_GPS(lv_event_t * e);
extern lv_obj_t * ui_GPS;
extern lv_obj_t * ui_TopBar8;
extern lv_obj_t * ui_ClockLabel8;
extern lv_obj_t * ui_BatteryGroup8;
extern lv_obj_t * ui_batteryIcon8;
extern lv_obj_t * ui_BatteryLable8;
extern lv_obj_t * ui_MainArea8;
extern lv_obj_t * ui_WifiLable8;
extern lv_obj_t * ui_WifiIcon9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

