// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_GPS = NULL;
lv_obj_t * ui_TopBar8 = NULL;
lv_obj_t * ui_ClockLabel8 = NULL;
lv_obj_t * ui_BatteryGroup8 = NULL;
lv_obj_t * ui_batteryIcon8 = NULL;
lv_obj_t * ui_BatteryLable8 = NULL;
lv_obj_t * ui_MainArea8 = NULL;
lv_obj_t * ui_WifiLable8 = NULL;
lv_obj_t * ui_WifiIcon9 = NULL;
// event funtions
void ui_event_GPS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_NRF24, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_NRF24_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Files, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Files_screen_init);
    }
}

// build funtions

void ui_GPS_screen_init(void)
{
    ui_GPS = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_GPS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar8 = lv_obj_create(ui_GPS);
    lv_obj_remove_style_all(ui_TopBar8);
    lv_obj_set_width(ui_TopBar8, 453);
    lv_obj_set_height(ui_TopBar8, 54);
    lv_obj_set_x(ui_TopBar8, -6);
    lv_obj_set_y(ui_TopBar8, -124);
    lv_obj_set_align(ui_TopBar8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopBar8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopBar8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TopBar8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockLabel8 = lv_label_create(ui_TopBar8);
    lv_obj_set_width(ui_ClockLabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel8, -1);
    lv_obj_set_y(ui_ClockLabel8, 0);
    lv_obj_set_align(ui_ClockLabel8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel8, "Clock");

    ui_BatteryGroup8 = lv_obj_create(ui_TopBar8);
    lv_obj_remove_style_all(ui_BatteryGroup8);
    lv_obj_set_width(ui_BatteryGroup8, 172);
    lv_obj_set_height(ui_BatteryGroup8, 38);
    lv_obj_set_x(ui_BatteryGroup8, -4);
    lv_obj_set_y(ui_BatteryGroup8, 8);
    lv_obj_set_align(ui_BatteryGroup8, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryGroup8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryGroup8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BatteryGroup8, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BatteryGroup8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryIcon8 = lv_image_create(ui_BatteryGroup8);
    lv_image_set_src(ui_batteryIcon8, &ui_img_battery_png);
    lv_obj_set_width(ui_batteryIcon8, 83);
    lv_obj_set_height(ui_batteryIcon8, 40);
    lv_obj_set_x(ui_batteryIcon8, -20);
    lv_obj_set_y(ui_batteryIcon8, 20);
    lv_obj_set_align(ui_batteryIcon8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_batteryIcon8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_batteryIcon8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_batteryIcon8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batteryIcon8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_batteryIcon8, 20);

    ui_BatteryLable8 = lv_label_create(ui_BatteryGroup8);
    lv_obj_set_width(ui_BatteryLable8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLable8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatteryLable8, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryLable8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryLable8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BatteryLable8, "Battery text");

    ui_MainArea8 = lv_obj_create(ui_GPS);
    lv_obj_remove_style_all(ui_MainArea8);
    lv_obj_set_width(ui_MainArea8, 321);
    lv_obj_set_height(ui_MainArea8, 230);
    lv_obj_set_x(ui_MainArea8, -69);
    lv_obj_set_y(ui_MainArea8, 8);
    lv_obj_set_align(ui_MainArea8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainArea8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLable8 = lv_label_create(ui_MainArea8);
    lv_obj_set_width(ui_WifiLable8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLable8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLable8, 1);
    lv_obj_set_y(ui_WifiLable8, -2);
    lv_obj_set_align(ui_WifiLable8, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WifiLable8, "GPS");
    lv_obj_set_style_text_color(ui_WifiLable8, lv_color_hex(0xD110E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLable8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon9 = lv_image_create(ui_MainArea8);
    lv_image_set_src(ui_WifiIcon9, &ui_img_gps_png);
    lv_obj_set_width(ui_WifiIcon9, 130);
    lv_obj_set_height(ui_WifiIcon9, 125);
    lv_obj_set_x(ui_WifiIcon9, 1);
    lv_obj_set_y(ui_WifiIcon9, 28);
    lv_obj_set_align(ui_WifiIcon9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIcon9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiIcon9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_WifiIcon9, 20, 20);
    lv_image_set_inner_align(ui_WifiIcon9, LV_IMAGE_ALIGN_TOP_LEFT);

    lv_obj_add_event_cb(ui_GPS, ui_event_GPS, LV_EVENT_ALL, NULL);

}

void ui_GPS_screen_destroy(void)
{
    if(ui_GPS) lv_obj_del(ui_GPS);

    // NULL screen variables
    ui_GPS = NULL;
    ui_TopBar8 = NULL;
    ui_ClockLabel8 = NULL;
    ui_BatteryGroup8 = NULL;
    ui_batteryIcon8 = NULL;
    ui_BatteryLable8 = NULL;
    ui_MainArea8 = NULL;
    ui_WifiLable8 = NULL;
    ui_WifiIcon9 = NULL;

}
