// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_INFRARED_H
#define UI_INFRARED_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_InfraRed
extern void ui_InfraRed_screen_init(void);
extern void ui_InfraRed_screen_destroy(void);
extern void ui_event_InfraRed(lv_event_t * e);
extern lv_obj_t * ui_InfraRed;
extern lv_obj_t * ui_TopBar5;
extern lv_obj_t * ui_ClockLabel5;
extern lv_obj_t * ui_BatteryGroup5;
extern lv_obj_t * ui_batteryIcon5;
extern lv_obj_t * ui_BatteryLable5;
extern lv_obj_t * ui_MainArea5;
extern lv_obj_t * ui_WifiLable5;
extern lv_obj_t * ui_WifiIcon6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

