// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_InfraRed = NULL;
lv_obj_t * ui_TopBar5 = NULL;
lv_obj_t * ui_ClockLabel5 = NULL;
lv_obj_t * ui_BatteryGroup5 = NULL;
lv_obj_t * ui_batteryIcon5 = NULL;
lv_obj_t * ui_BatteryLable5 = NULL;
lv_obj_t * ui_MainArea5 = NULL;
lv_obj_t * ui_WifiLable5 = NULL;
lv_obj_t * ui_WifiIcon6 = NULL;
// event funtions
void ui_event_InfraRed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_FMRadio, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_FMRadio_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_RFID, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_RFID_screen_init);
    }
}

// build funtions

void ui_InfraRed_screen_init(void)
{
    ui_InfraRed = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_InfraRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar5 = lv_obj_create(ui_InfraRed);
    lv_obj_remove_style_all(ui_TopBar5);
    lv_obj_set_width(ui_TopBar5, 453);
    lv_obj_set_height(ui_TopBar5, 54);
    lv_obj_set_x(ui_TopBar5, -6);
    lv_obj_set_y(ui_TopBar5, -124);
    lv_obj_set_align(ui_TopBar5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopBar5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopBar5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TopBar5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockLabel5 = lv_label_create(ui_TopBar5);
    lv_obj_set_width(ui_ClockLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel5, -1);
    lv_obj_set_y(ui_ClockLabel5, 0);
    lv_obj_set_align(ui_ClockLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel5, "Clock");

    ui_BatteryGroup5 = lv_obj_create(ui_TopBar5);
    lv_obj_remove_style_all(ui_BatteryGroup5);
    lv_obj_set_width(ui_BatteryGroup5, 172);
    lv_obj_set_height(ui_BatteryGroup5, 38);
    lv_obj_set_x(ui_BatteryGroup5, -4);
    lv_obj_set_y(ui_BatteryGroup5, 8);
    lv_obj_set_align(ui_BatteryGroup5, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryGroup5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryGroup5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BatteryGroup5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BatteryGroup5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryIcon5 = lv_image_create(ui_BatteryGroup5);
    lv_image_set_src(ui_batteryIcon5, &ui_img_battery_png);
    lv_obj_set_width(ui_batteryIcon5, 83);
    lv_obj_set_height(ui_batteryIcon5, 40);
    lv_obj_set_x(ui_batteryIcon5, -20);
    lv_obj_set_y(ui_batteryIcon5, 20);
    lv_obj_set_align(ui_batteryIcon5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_batteryIcon5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_batteryIcon5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_batteryIcon5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batteryIcon5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_batteryIcon5, 20);

    ui_BatteryLable5 = lv_label_create(ui_BatteryGroup5);
    lv_obj_set_width(ui_BatteryLable5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLable5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatteryLable5, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryLable5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryLable5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BatteryLable5, "Battery text");

    ui_MainArea5 = lv_obj_create(ui_InfraRed);
    lv_obj_remove_style_all(ui_MainArea5);
    lv_obj_set_width(ui_MainArea5, 321);
    lv_obj_set_height(ui_MainArea5, 230);
    lv_obj_set_x(ui_MainArea5, -69);
    lv_obj_set_y(ui_MainArea5, 8);
    lv_obj_set_align(ui_MainArea5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainArea5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLable5 = lv_label_create(ui_MainArea5);
    lv_obj_set_width(ui_WifiLable5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLable5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLable5, 1);
    lv_obj_set_y(ui_WifiLable5, -2);
    lv_obj_set_align(ui_WifiLable5, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WifiLable5, "IR");
    lv_obj_set_style_text_color(ui_WifiLable5, lv_color_hex(0xD110E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLable5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon6 = lv_image_create(ui_MainArea5);
    lv_image_set_src(ui_WifiIcon6, &ui_img_infrared_png);
    lv_obj_set_width(ui_WifiIcon6, 159);
    lv_obj_set_height(ui_WifiIcon6, 156);
    lv_obj_set_x(ui_WifiIcon6, -6);
    lv_obj_set_y(ui_WifiIcon6, 14);
    lv_obj_set_align(ui_WifiIcon6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIcon6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiIcon6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_WifiIcon6, 20, 20);
    lv_image_set_scale(ui_WifiIcon6, 80);
    lv_image_set_inner_align(ui_WifiIcon6, LV_IMAGE_ALIGN_TOP_LEFT);

    lv_obj_add_event_cb(ui_InfraRed, ui_event_InfraRed, LV_EVENT_ALL, NULL);

}

void ui_InfraRed_screen_destroy(void)
{
    if(ui_InfraRed) lv_obj_del(ui_InfraRed);

    // NULL screen variables
    ui_InfraRed = NULL;
    ui_TopBar5 = NULL;
    ui_ClockLabel5 = NULL;
    ui_BatteryGroup5 = NULL;
    ui_batteryIcon5 = NULL;
    ui_BatteryLable5 = NULL;
    ui_MainArea5 = NULL;
    ui_WifiLable5 = NULL;
    ui_WifiIcon6 = NULL;

}
