// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_JSINTERPRETER_H
#define UI_JSINTERPRETER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_JSInterpreter
extern void ui_JSInterpreter_screen_init(void);
extern void ui_JSInterpreter_screen_destroy(void);
extern void ui_event_JSInterpreter(lv_event_t * e);
extern lv_obj_t * ui_JSInterpreter;
extern lv_obj_t * ui_TopBar10;
extern lv_obj_t * ui_ClockLabel10;
extern lv_obj_t * ui_BatteryGroup10;
extern lv_obj_t * ui_batteryIcon10;
extern lv_obj_t * ui_BatteryLable10;
extern lv_obj_t * ui_MainArea10;
extern lv_obj_t * ui_WifiLable10;
extern lv_obj_t * ui_WifiIcon11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

