// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_JSInterpreter = NULL;
lv_obj_t * ui_TopBar10 = NULL;
lv_obj_t * ui_ClockLabel10 = NULL;
lv_obj_t * ui_BatteryGroup10 = NULL;
lv_obj_t * ui_batteryIcon10 = NULL;
lv_obj_t * ui_BatteryLable10 = NULL;
lv_obj_t * ui_MainArea10 = NULL;
lv_obj_t * ui_WifiLable10 = NULL;
lv_obj_t * ui_WifiIcon11 = NULL;
// event funtions
void ui_event_JSInterpreter(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_LORA, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_LORA_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_NRF24, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_NRF24_screen_init);
    }
}

// build funtions

void ui_JSInterpreter_screen_init(void)
{
    ui_JSInterpreter = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_JSInterpreter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar10 = lv_obj_create(ui_JSInterpreter);
    lv_obj_remove_style_all(ui_TopBar10);
    lv_obj_set_width(ui_TopBar10, 453);
    lv_obj_set_height(ui_TopBar10, 54);
    lv_obj_set_x(ui_TopBar10, -6);
    lv_obj_set_y(ui_TopBar10, -124);
    lv_obj_set_align(ui_TopBar10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopBar10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopBar10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TopBar10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockLabel10 = lv_label_create(ui_TopBar10);
    lv_obj_set_width(ui_ClockLabel10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel10, -1);
    lv_obj_set_y(ui_ClockLabel10, 0);
    lv_obj_set_align(ui_ClockLabel10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel10, "Clock");

    ui_BatteryGroup10 = lv_obj_create(ui_TopBar10);
    lv_obj_remove_style_all(ui_BatteryGroup10);
    lv_obj_set_width(ui_BatteryGroup10, 172);
    lv_obj_set_height(ui_BatteryGroup10, 38);
    lv_obj_set_x(ui_BatteryGroup10, -4);
    lv_obj_set_y(ui_BatteryGroup10, 8);
    lv_obj_set_align(ui_BatteryGroup10, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryGroup10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryGroup10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BatteryGroup10, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BatteryGroup10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryIcon10 = lv_image_create(ui_BatteryGroup10);
    lv_image_set_src(ui_batteryIcon10, &ui_img_battery_png);
    lv_obj_set_width(ui_batteryIcon10, 83);
    lv_obj_set_height(ui_batteryIcon10, 40);
    lv_obj_set_x(ui_batteryIcon10, -20);
    lv_obj_set_y(ui_batteryIcon10, 20);
    lv_obj_set_align(ui_batteryIcon10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_batteryIcon10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_batteryIcon10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_batteryIcon10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batteryIcon10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_batteryIcon10, 20);

    ui_BatteryLable10 = lv_label_create(ui_BatteryGroup10);
    lv_obj_set_width(ui_BatteryLable10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLable10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatteryLable10, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryLable10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryLable10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BatteryLable10, "Battery text");

    ui_MainArea10 = lv_obj_create(ui_JSInterpreter);
    lv_obj_remove_style_all(ui_MainArea10);
    lv_obj_set_width(ui_MainArea10, 321);
    lv_obj_set_height(ui_MainArea10, 230);
    lv_obj_set_x(ui_MainArea10, -69);
    lv_obj_set_y(ui_MainArea10, 8);
    lv_obj_set_align(ui_MainArea10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainArea10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLable10 = lv_label_create(ui_MainArea10);
    lv_obj_set_width(ui_WifiLable10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLable10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLable10, 1);
    lv_obj_set_y(ui_WifiLable10, -2);
    lv_obj_set_align(ui_WifiLable10, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WifiLable10, "JS Interpreter");
    lv_obj_set_style_text_color(ui_WifiLable10, lv_color_hex(0xD110E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLable10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon11 = lv_image_create(ui_MainArea10);
    lv_image_set_src(ui_WifiIcon11, &ui_img_blu_png);
    lv_obj_set_width(ui_WifiIcon11, 130);
    lv_obj_set_height(ui_WifiIcon11, 125);
    lv_obj_set_x(ui_WifiIcon11, 1);
    lv_obj_set_y(ui_WifiIcon11, 28);
    lv_obj_set_align(ui_WifiIcon11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIcon11, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiIcon11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_WifiIcon11, 20, 20);
    lv_image_set_inner_align(ui_WifiIcon11, LV_IMAGE_ALIGN_TOP_LEFT);

    lv_obj_add_event_cb(ui_JSInterpreter, ui_event_JSInterpreter, LV_EVENT_ALL, NULL);

}

void ui_JSInterpreter_screen_destroy(void)
{
    if(ui_JSInterpreter) lv_obj_del(ui_JSInterpreter);

    // NULL screen variables
    ui_JSInterpreter = NULL;
    ui_TopBar10 = NULL;
    ui_ClockLabel10 = NULL;
    ui_BatteryGroup10 = NULL;
    ui_batteryIcon10 = NULL;
    ui_BatteryLable10 = NULL;
    ui_MainArea10 = NULL;
    ui_WifiLable10 = NULL;
    ui_WifiIcon11 = NULL;

}
