// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_LORA_H
#define UI_LORA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LORA
extern void ui_LORA_screen_init(void);
extern void ui_LORA_screen_destroy(void);
extern void ui_event_LORA(lv_event_t * e);
extern lv_obj_t * ui_LORA;
extern lv_obj_t * ui_TopBar11;
extern lv_obj_t * ui_ClockLabel11;
extern lv_obj_t * ui_BatteryGroup11;
extern lv_obj_t * ui_batteryIcon11;
extern lv_obj_t * ui_BatteryLable11;
extern lv_obj_t * ui_MainArea11;
extern lv_obj_t * ui_WifiLable11;
extern lv_obj_t * ui_WifiIcon12;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

