// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_NRF24_H
#define UI_NRF24_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_NRF24
extern void ui_NRF24_screen_init(void);
extern void ui_NRF24_screen_destroy(void);
extern void ui_event_NRF24(lv_event_t * e);
extern lv_obj_t * ui_NRF24;
extern lv_obj_t * ui_TopBar9;
extern lv_obj_t * ui_ClockLabel9;
extern lv_obj_t * ui_BatteryGroup9;
extern lv_obj_t * ui_batteryIcon9;
extern lv_obj_t * ui_BatteryLable9;
extern lv_obj_t * ui_MainArea9;
extern lv_obj_t * ui_WifiLable9;
extern lv_obj_t * ui_WifiIcon10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

