// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_NRF24 = NULL;
lv_obj_t * ui_TopBar9 = NULL;
lv_obj_t * ui_ClockLabel9 = NULL;
lv_obj_t * ui_BatteryGroup9 = NULL;
lv_obj_t * ui_batteryIcon9 = NULL;
lv_obj_t * ui_BatteryLable9 = NULL;
lv_obj_t * ui_MainArea9 = NULL;
lv_obj_t * ui_WifiLable9 = NULL;
lv_obj_t * ui_WifiIcon10 = NULL;
// event funtions
void ui_event_NRF24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_JSInterpreter, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_JSInterpreter_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_GPS, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_GPS_screen_init);
    }
}

// build funtions

void ui_NRF24_screen_init(void)
{
    ui_NRF24 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_NRF24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar9 = lv_obj_create(ui_NRF24);
    lv_obj_remove_style_all(ui_TopBar9);
    lv_obj_set_width(ui_TopBar9, 453);
    lv_obj_set_height(ui_TopBar9, 54);
    lv_obj_set_x(ui_TopBar9, -6);
    lv_obj_set_y(ui_TopBar9, -124);
    lv_obj_set_align(ui_TopBar9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopBar9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopBar9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TopBar9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockLabel9 = lv_label_create(ui_TopBar9);
    lv_obj_set_width(ui_ClockLabel9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel9, -1);
    lv_obj_set_y(ui_ClockLabel9, 0);
    lv_obj_set_align(ui_ClockLabel9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel9, "Clock");

    ui_BatteryGroup9 = lv_obj_create(ui_TopBar9);
    lv_obj_remove_style_all(ui_BatteryGroup9);
    lv_obj_set_width(ui_BatteryGroup9, 172);
    lv_obj_set_height(ui_BatteryGroup9, 38);
    lv_obj_set_x(ui_BatteryGroup9, -4);
    lv_obj_set_y(ui_BatteryGroup9, 8);
    lv_obj_set_align(ui_BatteryGroup9, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryGroup9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryGroup9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BatteryGroup9, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BatteryGroup9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryIcon9 = lv_image_create(ui_BatteryGroup9);
    lv_image_set_src(ui_batteryIcon9, &ui_img_battery_png);
    lv_obj_set_width(ui_batteryIcon9, 83);
    lv_obj_set_height(ui_batteryIcon9, 40);
    lv_obj_set_x(ui_batteryIcon9, -20);
    lv_obj_set_y(ui_batteryIcon9, 20);
    lv_obj_set_align(ui_batteryIcon9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_batteryIcon9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_batteryIcon9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_batteryIcon9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batteryIcon9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_batteryIcon9, 20);

    ui_BatteryLable9 = lv_label_create(ui_BatteryGroup9);
    lv_obj_set_width(ui_BatteryLable9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLable9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatteryLable9, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryLable9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryLable9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BatteryLable9, "Battery text");

    ui_MainArea9 = lv_obj_create(ui_NRF24);
    lv_obj_remove_style_all(ui_MainArea9);
    lv_obj_set_width(ui_MainArea9, 321);
    lv_obj_set_height(ui_MainArea9, 230);
    lv_obj_set_x(ui_MainArea9, -69);
    lv_obj_set_y(ui_MainArea9, 8);
    lv_obj_set_align(ui_MainArea9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainArea9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLable9 = lv_label_create(ui_MainArea9);
    lv_obj_set_width(ui_WifiLable9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLable9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLable9, 1);
    lv_obj_set_y(ui_WifiLable9, -2);
    lv_obj_set_align(ui_WifiLable9, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WifiLable9, "NRF24");
    lv_obj_set_style_text_color(ui_WifiLable9, lv_color_hex(0xD110E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLable9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon10 = lv_image_create(ui_MainArea9);
    lv_image_set_src(ui_WifiIcon10, &ui_img_blu_png);
    lv_obj_set_width(ui_WifiIcon10, 130);
    lv_obj_set_height(ui_WifiIcon10, 125);
    lv_obj_set_x(ui_WifiIcon10, 1);
    lv_obj_set_y(ui_WifiIcon10, 28);
    lv_obj_set_align(ui_WifiIcon10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIcon10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiIcon10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_WifiIcon10, 20, 20);
    lv_image_set_inner_align(ui_WifiIcon10, LV_IMAGE_ALIGN_TOP_LEFT);

    lv_obj_add_event_cb(ui_NRF24, ui_event_NRF24, LV_EVENT_ALL, NULL);

}

void ui_NRF24_screen_destroy(void)
{
    if(ui_NRF24) lv_obj_del(ui_NRF24);

    // NULL screen variables
    ui_NRF24 = NULL;
    ui_TopBar9 = NULL;
    ui_ClockLabel9 = NULL;
    ui_BatteryGroup9 = NULL;
    ui_batteryIcon9 = NULL;
    ui_BatteryLable9 = NULL;
    ui_MainArea9 = NULL;
    ui_WifiLable9 = NULL;
    ui_WifiIcon10 = NULL;

}
