// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Others = NULL;
lv_obj_t * ui_TopBar12 = NULL;
lv_obj_t * ui_ClockLabel12 = NULL;
lv_obj_t * ui_BatteryGroup12 = NULL;
lv_obj_t * ui_batteryIcon12 = NULL;
lv_obj_t * ui_BatteryLable12 = NULL;
lv_obj_t * ui_MainArea12 = NULL;
lv_obj_t * ui_WifiLable12 = NULL;
lv_obj_t * ui_WifiIcon13 = NULL;
// event funtions
void ui_event_Others(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Clock, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Clock_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_LORA, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_LORA_screen_init);
    }
}

// build funtions

void ui_Others_screen_init(void)
{
    ui_Others = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Others, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar12 = lv_obj_create(ui_Others);
    lv_obj_remove_style_all(ui_TopBar12);
    lv_obj_set_width(ui_TopBar12, 453);
    lv_obj_set_height(ui_TopBar12, 54);
    lv_obj_set_x(ui_TopBar12, -6);
    lv_obj_set_y(ui_TopBar12, -124);
    lv_obj_set_align(ui_TopBar12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopBar12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopBar12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TopBar12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockLabel12 = lv_label_create(ui_TopBar12);
    lv_obj_set_width(ui_ClockLabel12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel12, -1);
    lv_obj_set_y(ui_ClockLabel12, 0);
    lv_obj_set_align(ui_ClockLabel12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel12, "Clock");

    ui_BatteryGroup12 = lv_obj_create(ui_TopBar12);
    lv_obj_remove_style_all(ui_BatteryGroup12);
    lv_obj_set_width(ui_BatteryGroup12, 172);
    lv_obj_set_height(ui_BatteryGroup12, 38);
    lv_obj_set_x(ui_BatteryGroup12, -4);
    lv_obj_set_y(ui_BatteryGroup12, 8);
    lv_obj_set_align(ui_BatteryGroup12, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryGroup12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryGroup12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BatteryGroup12, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BatteryGroup12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryIcon12 = lv_image_create(ui_BatteryGroup12);
    lv_image_set_src(ui_batteryIcon12, &ui_img_battery_png);
    lv_obj_set_width(ui_batteryIcon12, 83);
    lv_obj_set_height(ui_batteryIcon12, 40);
    lv_obj_set_x(ui_batteryIcon12, -20);
    lv_obj_set_y(ui_batteryIcon12, 20);
    lv_obj_set_align(ui_batteryIcon12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_batteryIcon12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_batteryIcon12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_batteryIcon12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batteryIcon12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_batteryIcon12, 20);

    ui_BatteryLable12 = lv_label_create(ui_BatteryGroup12);
    lv_obj_set_width(ui_BatteryLable12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLable12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatteryLable12, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryLable12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryLable12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BatteryLable12, "Battery text");

    ui_MainArea12 = lv_obj_create(ui_Others);
    lv_obj_remove_style_all(ui_MainArea12);
    lv_obj_set_width(ui_MainArea12, 321);
    lv_obj_set_height(ui_MainArea12, 230);
    lv_obj_set_x(ui_MainArea12, -69);
    lv_obj_set_y(ui_MainArea12, 8);
    lv_obj_set_align(ui_MainArea12, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainArea12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLable12 = lv_label_create(ui_MainArea12);
    lv_obj_set_width(ui_WifiLable12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLable12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLable12, 1);
    lv_obj_set_y(ui_WifiLable12, -2);
    lv_obj_set_align(ui_WifiLable12, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WifiLable12, "Others");
    lv_obj_set_style_text_color(ui_WifiLable12, lv_color_hex(0xD110E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLable12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon13 = lv_image_create(ui_MainArea12);
    lv_image_set_src(ui_WifiIcon13, &ui_img_others_png);
    lv_obj_set_width(ui_WifiIcon13, 130);
    lv_obj_set_height(ui_WifiIcon13, 125);
    lv_obj_set_x(ui_WifiIcon13, 1);
    lv_obj_set_y(ui_WifiIcon13, 28);
    lv_obj_set_align(ui_WifiIcon13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIcon13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiIcon13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_WifiIcon13, 20, 20);
    lv_image_set_inner_align(ui_WifiIcon13, LV_IMAGE_ALIGN_TOP_LEFT);

    lv_obj_add_event_cb(ui_Others, ui_event_Others, LV_EVENT_ALL, NULL);

}

void ui_Others_screen_destroy(void)
{
    if(ui_Others) lv_obj_del(ui_Others);

    // NULL screen variables
    ui_Others = NULL;
    ui_TopBar12 = NULL;
    ui_ClockLabel12 = NULL;
    ui_BatteryGroup12 = NULL;
    ui_batteryIcon12 = NULL;
    ui_BatteryLable12 = NULL;
    ui_MainArea12 = NULL;
    ui_WifiLable12 = NULL;
    ui_WifiIcon13 = NULL;

}
