// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_OTHERS_H
#define UI_OTHERS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Others
extern void ui_Others_screen_init(void);
extern void ui_Others_screen_destroy(void);
extern void ui_event_Others(lv_event_t * e);
extern lv_obj_t * ui_Others;
extern lv_obj_t * ui_TopBar12;
extern lv_obj_t * ui_ClockLabel12;
extern lv_obj_t * ui_BatteryGroup12;
extern lv_obj_t * ui_batteryIcon12;
extern lv_obj_t * ui_BatteryLable12;
extern lv_obj_t * ui_MainArea12;
extern lv_obj_t * ui_WifiLable12;
extern lv_obj_t * ui_WifiIcon13;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

