// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_RFID = NULL;
lv_obj_t * ui_TopBar4 = NULL;
lv_obj_t * ui_ClockLabel4 = NULL;
lv_obj_t * ui_BatteryGroup4 = NULL;
lv_obj_t * ui_batteryIcon4 = NULL;
lv_obj_t * ui_BatteryLable4 = NULL;
lv_obj_t * ui_MainArea4 = NULL;
lv_obj_t * ui_WifiLable4 = NULL;
lv_obj_t * ui_WifiIcon5 = NULL;
// event funtions
void ui_event_RFID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_InfraRed, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_InfraRed_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_RadioFreq, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_RadioFreq_screen_init);
    }
}

// build funtions

void ui_RFID_screen_init(void)
{
    ui_RFID = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_RFID, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar4 = lv_obj_create(ui_RFID);
    lv_obj_remove_style_all(ui_TopBar4);
    lv_obj_set_width(ui_TopBar4, 453);
    lv_obj_set_height(ui_TopBar4, 54);
    lv_obj_set_x(ui_TopBar4, -6);
    lv_obj_set_y(ui_TopBar4, -124);
    lv_obj_set_align(ui_TopBar4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopBar4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopBar4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TopBar4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockLabel4 = lv_label_create(ui_TopBar4);
    lv_obj_set_width(ui_ClockLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel4, -1);
    lv_obj_set_y(ui_ClockLabel4, 0);
    lv_obj_set_align(ui_ClockLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel4, "Clock");

    ui_BatteryGroup4 = lv_obj_create(ui_TopBar4);
    lv_obj_remove_style_all(ui_BatteryGroup4);
    lv_obj_set_width(ui_BatteryGroup4, 172);
    lv_obj_set_height(ui_BatteryGroup4, 38);
    lv_obj_set_x(ui_BatteryGroup4, -4);
    lv_obj_set_y(ui_BatteryGroup4, 8);
    lv_obj_set_align(ui_BatteryGroup4, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryGroup4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryGroup4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BatteryGroup4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BatteryGroup4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryIcon4 = lv_image_create(ui_BatteryGroup4);
    lv_image_set_src(ui_batteryIcon4, &ui_img_battery_png);
    lv_obj_set_width(ui_batteryIcon4, 83);
    lv_obj_set_height(ui_batteryIcon4, 40);
    lv_obj_set_x(ui_batteryIcon4, -20);
    lv_obj_set_y(ui_batteryIcon4, 20);
    lv_obj_set_align(ui_batteryIcon4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_batteryIcon4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_batteryIcon4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_batteryIcon4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batteryIcon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_batteryIcon4, 20);

    ui_BatteryLable4 = lv_label_create(ui_BatteryGroup4);
    lv_obj_set_width(ui_BatteryLable4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLable4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatteryLable4, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryLable4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryLable4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BatteryLable4, "Battery text");

    ui_MainArea4 = lv_obj_create(ui_RFID);
    lv_obj_remove_style_all(ui_MainArea4);
    lv_obj_set_width(ui_MainArea4, 321);
    lv_obj_set_height(ui_MainArea4, 230);
    lv_obj_set_x(ui_MainArea4, -69);
    lv_obj_set_y(ui_MainArea4, 8);
    lv_obj_set_align(ui_MainArea4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainArea4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLable4 = lv_label_create(ui_MainArea4);
    lv_obj_set_width(ui_WifiLable4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLable4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLable4, 1);
    lv_obj_set_y(ui_WifiLable4, -2);
    lv_obj_set_align(ui_WifiLable4, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WifiLable4, "RFID");
    lv_obj_set_style_text_color(ui_WifiLable4, lv_color_hex(0xD110E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLable4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon5 = lv_image_create(ui_MainArea4);
    lv_image_set_src(ui_WifiIcon5, &ui_img_rfid_png);
    lv_obj_set_width(ui_WifiIcon5, 130);
    lv_obj_set_height(ui_WifiIcon5, 125);
    lv_obj_set_x(ui_WifiIcon5, 1);
    lv_obj_set_y(ui_WifiIcon5, 28);
    lv_obj_set_align(ui_WifiIcon5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIcon5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiIcon5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_WifiIcon5, 20, 20);
    lv_image_set_inner_align(ui_WifiIcon5, LV_IMAGE_ALIGN_TOP_LEFT);

    lv_obj_add_event_cb(ui_RFID, ui_event_RFID, LV_EVENT_ALL, NULL);

}

void ui_RFID_screen_destroy(void)
{
    if(ui_RFID) lv_obj_del(ui_RFID);

    // NULL screen variables
    ui_RFID = NULL;
    ui_TopBar4 = NULL;
    ui_ClockLabel4 = NULL;
    ui_BatteryGroup4 = NULL;
    ui_batteryIcon4 = NULL;
    ui_BatteryLable4 = NULL;
    ui_MainArea4 = NULL;
    ui_WifiLable4 = NULL;
    ui_WifiIcon5 = NULL;

}
