// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_RFID_H
#define UI_RFID_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RFID
extern void ui_RFID_screen_init(void);
extern void ui_RFID_screen_destroy(void);
extern void ui_event_RFID(lv_event_t * e);
extern lv_obj_t * ui_RFID;
extern lv_obj_t * ui_TopBar4;
extern lv_obj_t * ui_ClockLabel4;
extern lv_obj_t * ui_BatteryGroup4;
extern lv_obj_t * ui_batteryIcon4;
extern lv_obj_t * ui_BatteryLable4;
extern lv_obj_t * ui_MainArea4;
extern lv_obj_t * ui_WifiLable4;
extern lv_obj_t * ui_WifiIcon5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

