// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_RadioFreq = NULL;
lv_obj_t * ui_TopBar3 = NULL;
lv_obj_t * ui_ClockLabel3 = NULL;
lv_obj_t * ui_BatteryGroup3 = NULL;
lv_obj_t * ui_batteryIcon3 = NULL;
lv_obj_t * ui_BatteryLable3 = NULL;
lv_obj_t * ui_MainArea3 = NULL;
lv_obj_t * ui_WifiLable3 = NULL;
lv_obj_t * ui_WifiIcon4 = NULL;
// event funtions
void ui_event_RadioFreq(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_RFID, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_RFID_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Ethernet, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Ethernet_screen_init);
    }
}

// build funtions

void ui_RadioFreq_screen_init(void)
{
    ui_RadioFreq = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_RadioFreq, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar3 = lv_obj_create(ui_RadioFreq);
    lv_obj_remove_style_all(ui_TopBar3);
    lv_obj_set_width(ui_TopBar3, 453);
    lv_obj_set_height(ui_TopBar3, 54);
    lv_obj_set_x(ui_TopBar3, -6);
    lv_obj_set_y(ui_TopBar3, -124);
    lv_obj_set_align(ui_TopBar3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopBar3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopBar3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TopBar3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockLabel3 = lv_label_create(ui_TopBar3);
    lv_obj_set_width(ui_ClockLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel3, -1);
    lv_obj_set_y(ui_ClockLabel3, 0);
    lv_obj_set_align(ui_ClockLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel3, "Clock");

    ui_BatteryGroup3 = lv_obj_create(ui_TopBar3);
    lv_obj_remove_style_all(ui_BatteryGroup3);
    lv_obj_set_width(ui_BatteryGroup3, 172);
    lv_obj_set_height(ui_BatteryGroup3, 38);
    lv_obj_set_x(ui_BatteryGroup3, -4);
    lv_obj_set_y(ui_BatteryGroup3, 8);
    lv_obj_set_align(ui_BatteryGroup3, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryGroup3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryGroup3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BatteryGroup3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BatteryGroup3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryIcon3 = lv_image_create(ui_BatteryGroup3);
    lv_image_set_src(ui_batteryIcon3, &ui_img_battery_png);
    lv_obj_set_width(ui_batteryIcon3, 83);
    lv_obj_set_height(ui_batteryIcon3, 40);
    lv_obj_set_x(ui_batteryIcon3, -20);
    lv_obj_set_y(ui_batteryIcon3, 20);
    lv_obj_set_align(ui_batteryIcon3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_batteryIcon3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_batteryIcon3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_batteryIcon3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batteryIcon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_batteryIcon3, 20);

    ui_BatteryLable3 = lv_label_create(ui_BatteryGroup3);
    lv_obj_set_width(ui_BatteryLable3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLable3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatteryLable3, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryLable3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryLable3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BatteryLable3, "Battery text");

    ui_MainArea3 = lv_obj_create(ui_RadioFreq);
    lv_obj_remove_style_all(ui_MainArea3);
    lv_obj_set_width(ui_MainArea3, 321);
    lv_obj_set_height(ui_MainArea3, 230);
    lv_obj_set_x(ui_MainArea3, -69);
    lv_obj_set_y(ui_MainArea3, 8);
    lv_obj_set_align(ui_MainArea3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainArea3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLable3 = lv_label_create(ui_MainArea3);
    lv_obj_set_width(ui_WifiLable3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLable3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLable3, 1);
    lv_obj_set_y(ui_WifiLable3, -2);
    lv_obj_set_align(ui_WifiLable3, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WifiLable3, "RF");
    lv_obj_set_style_text_color(ui_WifiLable3, lv_color_hex(0xD110E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLable3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon4 = lv_image_create(ui_MainArea3);
    lv_image_set_src(ui_WifiIcon4, &ui_img_antenna_936483_png);
    lv_obj_set_width(ui_WifiIcon4, 130);
    lv_obj_set_height(ui_WifiIcon4, 125);
    lv_obj_set_x(ui_WifiIcon4, 1);
    lv_obj_set_y(ui_WifiIcon4, 28);
    lv_obj_set_align(ui_WifiIcon4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIcon4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiIcon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_WifiIcon4, 20, 20);
    lv_image_set_inner_align(ui_WifiIcon4, LV_IMAGE_ALIGN_TOP_LEFT);

    lv_obj_add_event_cb(ui_RadioFreq, ui_event_RadioFreq, LV_EVENT_ALL, NULL);

}

void ui_RadioFreq_screen_destroy(void)
{
    if(ui_RadioFreq) lv_obj_del(ui_RadioFreq);

    // NULL screen variables
    ui_RadioFreq = NULL;
    ui_TopBar3 = NULL;
    ui_ClockLabel3 = NULL;
    ui_BatteryGroup3 = NULL;
    ui_batteryIcon3 = NULL;
    ui_BatteryLable3 = NULL;
    ui_MainArea3 = NULL;
    ui_WifiLable3 = NULL;
    ui_WifiIcon4 = NULL;

}
