// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_RADIOFREQ_H
#define UI_RADIOFREQ_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RadioFreq
extern void ui_RadioFreq_screen_init(void);
extern void ui_RadioFreq_screen_destroy(void);
extern void ui_event_RadioFreq(lv_event_t * e);
extern lv_obj_t * ui_RadioFreq;
extern lv_obj_t * ui_TopBar3;
extern lv_obj_t * ui_ClockLabel3;
extern lv_obj_t * ui_BatteryGroup3;
extern lv_obj_t * ui_batteryIcon3;
extern lv_obj_t * ui_BatteryLable3;
extern lv_obj_t * ui_MainArea3;
extern lv_obj_t * ui_WifiLable3;
extern lv_obj_t * ui_WifiIcon4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

