// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_WifiLable;
lv_obj_t * uic_MainArea;
lv_obj_t * uic_BatteryLable;
lv_obj_t * uic_batteryIcon;
lv_obj_t * uic_BatteryGroup;
lv_obj_t * uic_ClockLabel;
lv_obj_t * uic_WifiScreen;
lv_obj_t * ui_WifiScreen = NULL;
lv_obj_t * ui_TopBar = NULL;
lv_obj_t * ui_ClockLabel = NULL;
lv_obj_t * ui_BatteryGroup = NULL;
lv_obj_t * ui_batteryIcon = NULL;
lv_obj_t * ui_BatteryLable = NULL;
lv_obj_t * ui_MainArea = NULL;
lv_obj_t * ui_WifiLable = NULL;
lv_obj_t * ui_WifiIcon2 = NULL;
// event funtions
void ui_event_WifiScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_BluScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_BluScreen_screen_init);
    }
}

// build funtions

void ui_WifiScreen_screen_init(void)
{
    ui_WifiScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WifiScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar = lv_obj_create(ui_WifiScreen);
    lv_obj_remove_style_all(ui_TopBar);
    lv_obj_set_width(ui_TopBar, 453);
    lv_obj_set_height(ui_TopBar, 54);
    lv_obj_set_x(ui_TopBar, -6);
    lv_obj_set_y(ui_TopBar, -124);
    lv_obj_set_align(ui_TopBar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TopBar, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TopBar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TopBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockLabel = lv_label_create(ui_TopBar);
    lv_obj_set_width(ui_ClockLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel, -1);
    lv_obj_set_y(ui_ClockLabel, 0);
    lv_obj_set_align(ui_ClockLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel, "Clock");

    ui_BatteryGroup = lv_obj_create(ui_TopBar);
    lv_obj_remove_style_all(ui_BatteryGroup);
    lv_obj_set_width(ui_BatteryGroup, 172);
    lv_obj_set_height(ui_BatteryGroup, 38);
    lv_obj_set_x(ui_BatteryGroup, -4);
    lv_obj_set_y(ui_BatteryGroup, 8);
    lv_obj_set_align(ui_BatteryGroup, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryGroup, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryGroup, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BatteryGroup, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BatteryGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryIcon = lv_image_create(ui_BatteryGroup);
    lv_image_set_src(ui_batteryIcon, &ui_img_battery_png);
    lv_obj_set_width(ui_batteryIcon, 83);
    lv_obj_set_height(ui_batteryIcon, 40);
    lv_obj_set_x(ui_batteryIcon, -20);
    lv_obj_set_y(ui_batteryIcon, 20);
    lv_obj_set_align(ui_batteryIcon, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_batteryIcon, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_batteryIcon, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_batteryIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batteryIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_batteryIcon, 20);

    ui_BatteryLable = lv_label_create(ui_BatteryGroup);
    lv_obj_set_width(ui_BatteryLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatteryLable, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryLable, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryLable, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BatteryLable, "Battery text");

    ui_MainArea = lv_obj_create(ui_WifiScreen);
    lv_obj_remove_style_all(ui_MainArea);
    lv_obj_set_width(ui_MainArea, 321);
    lv_obj_set_height(ui_MainArea, 230);
    lv_obj_set_x(ui_MainArea, -69);
    lv_obj_set_y(ui_MainArea, 8);
    lv_obj_set_align(ui_MainArea, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLable = lv_label_create(ui_MainArea);
    lv_obj_set_width(ui_WifiLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLable, -1);
    lv_obj_set_y(ui_WifiLable, -2);
    lv_obj_set_align(ui_WifiLable, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WifiLable, "WIFI");
    lv_obj_set_style_text_color(ui_WifiLable, lv_color_hex(0xD110E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiLable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon2 = lv_image_create(ui_MainArea);
    lv_image_set_src(ui_WifiIcon2, &ui_img_wifi_png);
    lv_obj_set_width(ui_WifiIcon2, 130);
    lv_obj_set_height(ui_WifiIcon2, 125);
    lv_obj_set_x(ui_WifiIcon2, 1);
    lv_obj_set_y(ui_WifiIcon2, 28);
    lv_obj_set_align(ui_WifiIcon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIcon2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiIcon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_WifiIcon2, 20, 20);
    lv_image_set_inner_align(ui_WifiIcon2, LV_IMAGE_ALIGN_TOP_LEFT);

    lv_obj_add_event_cb(ui_WifiScreen, ui_event_WifiScreen, LV_EVENT_ALL, NULL);
    uic_WifiScreen = ui_WifiScreen;
    uic_ClockLabel = ui_ClockLabel;
    uic_BatteryGroup = ui_BatteryGroup;
    uic_batteryIcon = ui_batteryIcon;
    uic_BatteryLable = ui_BatteryLable;
    uic_MainArea = ui_MainArea;
    uic_WifiLable = ui_WifiLable;

}

void ui_WifiScreen_screen_destroy(void)
{
    if(ui_WifiScreen) lv_obj_del(ui_WifiScreen);

    // NULL screen variables
    uic_WifiScreen = NULL;
    ui_WifiScreen = NULL;
    ui_TopBar = NULL;
    uic_ClockLabel = NULL;
    ui_ClockLabel = NULL;
    uic_BatteryGroup = NULL;
    ui_BatteryGroup = NULL;
    uic_batteryIcon = NULL;
    ui_batteryIcon = NULL;
    uic_BatteryLable = NULL;
    ui_BatteryLable = NULL;
    uic_MainArea = NULL;
    ui_MainArea = NULL;
    uic_WifiLable = NULL;
    ui_WifiLable = NULL;
    ui_WifiIcon2 = NULL;

}
