// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_WIFISCREEN_H
#define UI_WIFISCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiScreen
extern void ui_WifiScreen_screen_init(void);
extern void ui_WifiScreen_screen_destroy(void);
extern void ui_event_WifiScreen(lv_event_t * e);
extern lv_obj_t * ui_WifiScreen;
extern lv_obj_t * ui_TopBar;
extern lv_obj_t * ui_ClockLabel;
extern lv_obj_t * ui_BatteryGroup;
extern lv_obj_t * ui_batteryIcon;
extern lv_obj_t * ui_BatteryLable;
extern lv_obj_t * ui_MainArea;
extern lv_obj_t * ui_WifiLable;
extern lv_obj_t * ui_WifiIcon2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_WifiScreen;
extern lv_obj_t * uic_ClockLabel;
extern lv_obj_t * uic_BatteryGroup;
extern lv_obj_t * uic_batteryIcon;
extern lv_obj_t * uic_BatteryLable;
extern lv_obj_t * uic_MainArea;
extern lv_obj_t * uic_WifiLable;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

