; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-waveshare-psram]
board = ESP-General
board_build.partitions = custom_8Mb.csv
board_build.arduino.memory_type = qio_opi  ; NEEDED FOR 8MB PSRAM (N16R8)
board_build.psram = enabled
build_src_filter =${env.build_src_filter} +<../boards/esp32s3_waveshare35>

monitor_port = COM4
monitor_speed = 115200


build_flags =
	${env.build_flags}
	-Iboards/esp32s3_waveshare35

	;TFT_eSPI display
	-DUSB_as_HID=1
	;-DHAS_SCREEN=1
	;-DHAS_TOUCH=1
    ;-DUSER_SETUP_LOADED=1
	-DUSE_HSPI_PORT=1
    -DTFT_RGB=1
	;-DST7796_DRIVER=1  # disable it if you are using Audrino_GFX
    -DCGRAM_OFFSET
    -DTFT_INVERSION_ON
	;-DSPI_FREQUENCY=80000000
	;-DARDUINO_USB_CDC_ON_BOOT=1

    -DLV_CONF_INCLUDE_SIMPLE
    -I .
    -DROTATION=1
	; grove pins
	; defaults from https://github.com/espressif/arduino-esp32/blob/master/variants/esp32s3/pins_arduino.h
	;-DALLOW_ALL_GPIO_FOR_IR_RF=1 ; Set this option to make use of all GPIOs, from 1 to 44 to be chosen, except TFT and SD pins

	; ir led pin
	-DIR_TX_PINS='{{"M5 IR Mod", GROVE_SDA}, {"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}}'
	-DIR_RX_PINS='{{"M5 IR Mod", GROVE_SCL}, {"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}}'
	-DTXLED=40
	-DLED_ON=HIGH
	-DLED_OFF=LOW

	;Radio Frequency (one pin modules) pin setting
	-DRF_TX_PINS='{{"M5 RF433T", GROVE_SDA}, {"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}}'
	-DRF_RX_PINS='{{"M5 RF433R", GROVE_SCL}, {"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}}'
	; sd card pins
	; suggested https://github.com/espressif/esp-idf/tree/master/examples/storage/sd_card/sdmmc
	;-DDEVICE_NAME='"ESP32-S3 DevkitC"'

lib_deps =
	${env.lib_deps}
	https://github.com/moononournation/Arduino_GFX.git
    lvgl/lvgl@^8.3.11
    https://github.com/lewisxhe/SensorLib.git
