// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_BootScreen.h"
#include "screens/ui_WifiScreen.h"
#include "screens/ui_BluScreen.h"
#include "screens/ui_Ethernet.h"
#include "screens/ui_RadioFreq.h"
#include "screens/ui_RFID.h"
#include "screens/ui_InfraRed.h"
#include "screens/ui_FMRadio.h"
#include "screens/ui_Files.h"
#include "screens/ui_GPS.h"
#include "screens/ui_NRF24.h"
#include "screens/ui_JSInterpreter.h"
#include "screens/ui_LORA.h"
#include "screens/ui_Others.h"
#include "screens/ui_Clock.h"
#include "screens/ui_Connect.h"
#include "screens/ui_Config.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bruce_hdc_png);    // assets/bruce_hdc.png
LV_IMG_DECLARE(ui_img_battery_png);    // assets/battery.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_blu_png);    // assets/blu.png
LV_IMG_DECLARE(ui_img_ethernet_png);    // assets/Ethernet.png
LV_IMG_DECLARE(ui_img_antenna_936483_png);    // assets/antenna_936483.png
LV_IMG_DECLARE(ui_img_rfid_png);    // assets/RFID.png
LV_IMG_DECLARE(ui_img_infrared_png);    // assets/Infrared.png
LV_IMG_DECLARE(ui_img_fm_png);    // assets/FM.png
LV_IMG_DECLARE(ui_img_files_png);    // assets/Files.png
LV_IMG_DECLARE(ui_img_gps_png);    // assets/GPS.png
LV_IMG_DECLARE(ui_img_lora_png);    // assets/LORA.png
LV_IMG_DECLARE(ui_img_others_png);    // assets/Others.png
LV_IMG_DECLARE(ui_img_clock_png);    // assets/Clock.png
LV_IMG_DECLARE(ui_img_connect_png);    // assets/Connect.png
LV_IMG_DECLARE(ui_img_config_png);    // assets/Config.png

// FONTS
LV_FONT_DECLARE(ui_font_UbuntuMedium);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
